"""add api tokens and resource scopes

Revision ID: 98b8daf381b3
Revises: c62ac7ad39bf
Create Date: 2026-08-13 20:26:33.978915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '98b8daf381b3'
down_revision: Union[str, None] = 'c62ac7ad39bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.Enum('all_resources', 'selected_resources', name='token_scope_type'), nullable=False),
    sa.Column('wrapped_data_key', sa.LargeBinary(), nullable=True),
    sa.Column('wrapped_data_key_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=False)
    op.create_table('api_token_resource_scopes',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_token_resource_scopes')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
    sa.Enum(name='token_scope_type').drop(op.get_bind(), checkfirst=True)
