"""add clients, resources, versions, notes, and access grants

Revision ID: c62ac7ad39bf
Revises: 5db9dabe954c
Create Date: 2026-08-13 20:07:05.271183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c62ac7ad39bf'
down_revision: Union[str, None] = '5db9dabe954c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, then hand-adjusted: resources and
    # resource_versions have a circular FK (resources.latest_version_id ->
    # resource_versions.id, resource_versions.resource_id -> resources.id).
    # Autogenerate can't topologically sort that, so both circular FKs are added
    # via separate create_foreign_key calls after both tables exist. ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('host', 'vm', 'storage', 'network_device', name='resource_type'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('latest_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending_delete', name='resource_status'), nullable=False),
    sa.Column('deleted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_resource_versions_resource_id', 'resource_versions', 'resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_resources_latest_version_id', 'resources', 'resource_versions', ['latest_version_id'], ['id'])
    op.create_table('resource_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_user_states',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=False),
    sa.Column('last_seen_version_id', sa.UUID(), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['resource_versions.id'], ),
    sa.ForeignKeyConstraint(['last_seen_version_id'], ['resource_versions.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'user_id')
    )
    op.create_table('client_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wrapped_data_key', sa.LargeBinary(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'user_id', name='uq_client_access_grants_client_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_access_grants')
    op.drop_table('resource_user_states')
    op.drop_table('resource_notes')
    op.drop_constraint('fk_resources_latest_version_id', 'resources', type_='foreignkey')
    op.drop_constraint('fk_resource_versions_resource_id', 'resource_versions', type_='foreignkey')
    op.drop_table('resources')
    op.drop_table('clients')
    op.drop_table('resource_versions')
    # ### end Alembic commands ###
    sa.Enum(name='resource_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='resource_status').drop(op.get_bind(), checkfirst=True)
