"""add client timeline entries

Revision ID: fd4e23e73232
Revises: 98b8daf381b3
Create Date: 2026-08-13 20:45:13.174956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd4e23e73232'
down_revision: Union[str, None] = '98b8daf381b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_timeline_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'email', 'future', name='timeline_entry_source'), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_timeline_entries')
    # ### end Alembic commands ###
    sa.Enum(name='timeline_entry_source').drop(op.get_bind(), checkfirst=True)
